# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :tests do
    run_tests(workspace: "TexDrive.xcworkspace",
    devices: ["iPhone 6s"],
    scheme: "TexDriveSDK")
  end
  desc "Description of what the lane does"
    lane :archivePod do
        xcodebuild(
        build: true,
        scheme: "Pods-TexDriveSDK",
        configuration: "Release-universal",
        clean: true,
        project: "Pods/Pods.xcodeproj",
        output_directory: "PodForSDK",
        sdk: "iphoneos"
        )
    end 
  desc "lane test"
  lane :initArchive do
    sh(
    "mkdir",
    "../universal"
    )
    sh(
    "mkdir",
    "../universal/Docs"
    )
  end
  desc "Description of what the lane does"
  lane :archive do
    xcodebuild(
        build: true,
        scheme: "TexDriveSDK",
        configuration: "Release-universal",
        workspace: "TexDrive.xcworkspace",
        derivedDataPath: "iphonesimulator",
        sdk: "iphonesimulator"
        )
    xcodebuild(
        build: true,
        scheme: "TexDriveSDK",
        configuration: "Release-universal",
        workspace: "TexDrive.xcworkspace",
        derivedDataPath: "iphoneos",
        sdk: "iphoneos"
        )
    sh(
            "cd", ".."
        )
    sh(
        "cp",
        "-R",
        "../iphoneos/Build/Products/Release-iphoneos/TexDriveSDK.framework",
        "../universal"
        )
    sh(
        "cp",
        "-R",
        "../iphonesimulator/Build/Products/Release-iphonesimulator/TexDriveSDK.framework/Modules/TexDriveSDK.swiftmodule/.",
        "../universal/TexDriveSDK.framework/Modules/TexDriveSDK.swiftmodule"
        )
    sh(
        "lipo",
        "-create",
        "-output",
        "../universal/TexDriveSDK.framework/TexDriveSDK",
        "../iphonesimulator/Build/Products/Release-iphonesimulator/TexDriveSDK.framework/TexDriveSDK",
        "../iphoneos/Build/Products/Release-iphoneos/TexDriveSDK.framework/TexDriveSDK"
        )

    sh(
        "rm",
        "-R",
        "../iphoneos"
        )
    sh(
        "rm",
        "-R",
        "../iphonesimulator"
        )

    sh(
        "cp",
        "-R",
        "../Docs/.",
        "../universal/Docs"
        )
    sh(
        "cp",
        "-R",
        "../CHANGELOG.md",
        "../universal"
        )
    sh(
        "cp",
        "-R",
        "../README.md",
        "../universal"
        )
    zip(
        path: "universal",
        output_path: "TexDriveSDK.zip"
    )
  end
end
